name: DrewAdams
favicon: null
layout_spectrum: 0.47516708355396986
typography_spectrum: 0.3861953425221145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.040732907596975565
  lightness: 0.3907708909828216
  saturation: 0.45600884035229683
  rhythmicContrast: 0.6730625831987709
purpose: []
